# Generated by Django 3.1 on 2021-10-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_fbatransaction_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbatransaction',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
