# Generated by Django 3.1 on 2021-10-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20211002_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbatransaction',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
